/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FntnConverterInterface extends ethers.utils.Interface {
  functions: {
    "shardIdToTokenId(uint256)": FunctionFragment;
    "tokenIdToShardId(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "shardIdToTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIdToShardId",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "shardIdToTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdToShardId",
    data: BytesLike
  ): Result;

  events: {};
}

export class FntnConverter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FntnConverterInterface;

  functions: {
    shardIdToTokenId(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "shardIdToTokenId(uint256)"(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    tokenIdToShardId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "tokenIdToShardId(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  shardIdToTokenId(
    shardId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "shardIdToTokenId(uint256)"(
    shardId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenIdToShardId(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "tokenIdToShardId(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    shardIdToTokenId(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "shardIdToTokenId(uint256)"(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenIdToShardId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenIdToShardId(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    shardIdToTokenId(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "shardIdToTokenId(uint256)"(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenIdToShardId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenIdToShardId(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    shardIdToTokenId(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "shardIdToTokenId(uint256)"(
      shardId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenIdToShardId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenIdToShardId(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
